# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/a77cdd47-8519-42d8-afa9-9d0dfb418cf4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/CB99-412B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/d9d42a3a-c52d-498e-bae8-9e88d52e1d49";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/f1d3a41d-e5ca-4b9f-b688-879ac6775bda"; }];

  # Basic networking configuration
  networking.useDHCP = lib.mkDefault true;
  networking.hostName = "d5424";

  # Dell rugged bug fix, CPU running at 10% of its theoretical speed
  # because of the BD PROCHOT signal
  services.throttled.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
